# YAML representation of Status API used as template for publishing
publish:
  space: A space
  logo: http://localhost/logo.svg
  url: http://localhost
  location:
    address: Somewhere
    lat: 56.68
    lon: 12.34
    timezone: Europe/Berlin
  contact:
    email: "foo@bar.local"
  projects: []

# Settings for administration
admin:
  # Enable admin routes
  # default: false
  enable: true
  # Set API key for access admin endpoint, if not set a random key will be
  # generated
  # default: generated and printed out
  #api_key: not-very-secure
  # Interval (in seconds) between two keep open calls before the space mark
  # automarically as closed
  # default: 300
  keep_open_interval: 300
  # Check interval (in milliseconds) for automatic state changes
  tick_interval: 100


# Configure status display output
status_display:
  # the content of `/status/text`
  text:
    # default text `open`
    open: space is open
    # default text `closed`
    closed: space is closed
  # the content of `/status/html`
  html:
    # default text `open`
    open: |
      <html>
        <body>
          <meta http-equiv="refresh" content="5">
          OPEN
        </body>
      </html>
    # default text `closed`
    closed: |
      <html>
        <body>
          <meta http-equiv="refresh" content="5">
          CLOSED
        </body>
      </html>
