name: Run on branch

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    container: rust:latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo test

  build:
    strategy:
      matrix:
        arch:
          - aarch64
          - x86_64
    runs-on: ubuntu-22.04
    container: rust:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.arch }}-unknown-linux-musl
