name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test:
    runs-on: ubuntu-22.04
    container: rust:latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo test

  binaries_x86-64:
    strategy:
      matrix:
        version:
          - "1.67"
        variant:
          - bullseye
          - bookworm
    runs-on: ubuntu-22.04
    container: rust:${{ matrix.version }}-${{ matrix.variant }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build binaries
        run: |
          apt-get update
          DEBCONF_FRONTEND=noninteractive apt-get upgrade -y
          cargo build --release

      - name: Archive binaries debian/${{ matrix.variant }} x86_64
        uses: actions/upload-artifact@v3
        with:
          name: debian-${{ matrix.variant }}
          path: |
            target/release/spaceapi-dezentrale-client
            target/release/spaceapi-dezentrale-server
     
  lint:
    runs-on: ubuntu-22.04
    container: rust:latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings

  fmt:
    runs-on: ubuntu-22.04
    container: rust:latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check
