name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-22.04
    container: rust:1.71
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy --all-targets --all-features -- -D warnings

  fmt:
    runs-on: ubuntu-22.04
    container: rust:1.71
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --all -- --check
