name: Run on main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    container: rust:latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo test

  binaries:
    strategy:
      matrix:
        - arch:
            - aarch64
            - x86_64
    runs-on: ubuntu-22.04
    container: rust:1.71
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build binaries
        run: |
          export DEBCONF_FRONTEND=noninteractive
          apt-get update
          apt-get upgrade --yes
          apt-get install --yes musl-tools
          cargo build --release --target ${{ matrix.arch }}-unknown-linux-musl

      - name: Archive server binaries
        uses: actions/upload-artifact@v3
        with:
          name: spaceapi-dezentrale-server-${{ matrix.arch }}
          path: |
            target/${{ matrix.arch }}-unknown-linux-musl/release/spaceapi-dezentrale-server

      - name: Archive client binaries
        uses: actions/upload-artifact@v3
        with:
          name: spaceapi-dezentrale-client-${{ matrix.arch }}
          path: |
            target/${{ matrix.arch }}-unknown-linux-musl/release/spaceapi-dezentrale-client
     
  lint:
    runs-on: ubuntu-22.04
    container: rust:latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings

  fmt:
    runs-on: ubuntu-22.04
    container: rust:latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check
