name: Publish release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release on GitHub
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

  build:
    name: Build binaries
    needs: release
    strategy:
      matrix:
        include:
          - arch: aarch64
            rust_target: aarch64-unknown-linux-musl
            packages: gcc-aarch64-linux-gnu musl-tools
          - arch: armv6
            rust_target: arm-unknown-linux-musleabihf
            packages: gcc-arm-linux-gnueabihf musl-tools
          - arch: armv7
            rust_target: armv7-unknown-linux-musleabihf
            packages: gcc-arm-linux-gnueabihf musl-tools
          - arch: x86_64
            rust_target: x86_64-unknown-linux-musl
            packages: musl-tools
    runs-on: ubuntu-latest
    container: rust:1.72-bookworm
    steps:
      - uses: actions/checkout@v2

      - name: Cargo build
        run: |
          export DEBCONF_FRONTEND=noninteractive
          #apt-get update
          #apt-get upgrade --yes
          #apt-get install --yes ${{ matrix.packages }}
          #cargo build --bins --target "${{ matrix.rust_target }}" --release
          mkdir -p "target/${{ matrix.rust_target }}/release"
          touch spaceapi-dezentrale-client
          touch spaceapi-dezentrale-server
          cd "target/${{ matrix.rust_target }}/release"
          sha256sum spaceapi-dezentrale-client >spaceapi-dezentrale-client.sha256
          sha256sum spaceapi-dezentrale-server >spaceapi-dezentrale-server.sha256

      - name: Store client binaries as artifact
        uses: actions/upload-artifact@v3
        with:
          name: binaries-${{ matrix.arch }}
          path: |
            target/${{ matrix.rust_target }}/release/spaceapi-dezentrale-client
            target/${{ matrix.rust_target }}/release/spaceapi-dezentrale-server

      - name: Append client binary to release page
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_name: spaceapi-dezentrale-client-${{ matrix.arch }}
          asset_path: target/${{ matrix.rust_target }}/release/spaceapi-dezentrale-client
          asset_content_type: application/x-executable

      - name: Append client binary checksum to release page
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_name: spaceapi-dezentrale-client-${{ matrix.arch }}.sha256
          asset_path: target/${{ matrix.rust_target }}/release/spaceapi-dezentrale-client.sha256
          asset_content_type: text/plain

      - name: Append server binary to release page
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_name: spaceapi-dezentrale-server-${{ matrix.arch }}
          asset_path: target/${{ matrix.rust_target }}/release/spaceapi-dezentrale-server
          asset_content_type: text/plain

      - name: Append server binary checksum to release page
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_name: spaceapi-dezentrale-server-${{ matrix.arch }}.sha256
          asset_path: target/${{ matrix.rust_target }}/release/spaceapi-dezentrale-server.sha256
          asset_content_type: text/plain

  container:
    name: Build images
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: aarch64
            rust_target: aarch64-unknown-linux-musl
            docker_platform: linux/arm64v8
          - arch: armv6
            rust_target: arm-unknown-linux-musleabihf
            docker_platform: linux/arm32v6
          - arch: armv7
            rust_target: armv7-unknown-linux-musleabihf
            docker_platform: linux/arm32v7
          - arch: x86_64
            rust_target: armv7-unknown-linux-musleabihf
            docker_platform: linux/amd64
    steps:
      - uses: actions/checkout@v2

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries-${{ matrix.arch }}
          path: target/${{ matrix.rust_target }}/release

      - run: |
          pwd
          tree target

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push client to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            TARGET=${{ matrix.rust_target }}
            BUILD_TYPE=release
          platforms: ${{ matrix.docker_platform }}
          file: Dockerfile.client
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/spaceapi-dezentrale-client:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/spaceapi-dezentrale-client:${{ github.ref_name }}

      - name: Build and push server to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            TARGET=${{ matrix.rust_target }}
            BUILD_TYPE=release
          platforms: ${{ matrix.docker_platform }}
          file: Dockerfile.server
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/spaceapi-dezentrale-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/spaceapi-dezentrale-server:${{ github.ref_name }}
