name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build:
    name: Build binaries
    needs: release
    strategy:
      matrix:
        include:
          - arch: aarch64
            target: aarch64-unknown-linux-musl
            packages: "gcc-aarch64-linux-gnu musl-tools"
          - arch: armv6
            target: arm-unknown-linux-musleabihf
            packages: "gcc-arm-linux-gnueabihf musl-tools"
          - arch: armv7
            target: armv7-unknown-linux-musleabihf
            packages: "gcc-arm-linux-gnueabihf musl-tools"
          - arch: x86_64
            target: x86_64-unknown-linux-musl
            packages: "musl-tools"
    runs-on: ubuntu-latest
    container: rust:1.71-bookworm
    steps:
      - uses: actions/checkout@v2

      - run: |
          export DEBCONF_FRONTEND=noninteractive
          apt-get update
          apt-get upgrade --yes
          apt-get install --yes ${{ matrix.packages }}
          cargo build --bins --target "${arch}" --release

      - uses: actions/upload-artifact@v3
        with:
          name: "spaceapi-dezentrale-client-${arch}"
          path: "target/${arch}/release/spaceapi-dezentrale-client"

      - uses: actions/upload-artifact@v3
        with:
          name: "spaceapi-dezentrale-server-${arch}"
          path: "target/${arch}/release/spaceapi-dezentrale-server"

  upload:
    name: Upload binaries to release
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: spaceapi-dezentrale-client-x86_64

      - uses: actions/download-artifact@v3
        with:
          name: spaceapi-dezentrale-client-aarch64

      - uses: actions/download-artifact@v3
        with:
          name: spaceapi-dezentrale-client-arm

      - uses: actions/download-artifact@v3
        with:
          name: spaceapi-dezentrale-client-armv7

      - uses: actions/download-artifact@v3
        with:
          name: spaceapi-dezentrale-server-x86_64

      - uses: actions/download-artifact@v3
        with:
          name: spaceapi-dezentrale-server-aarch64

      - uses: actions/download-artifact@v3
        with:
          name: spaceapi-dezentrale-server-arm

      - uses: actions/download-artifact@v3
        with:
          name: spaceapi-dezentrale-server-armv7

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for arch in x86_64 aarch64 arm-unknown armv7 ; do
            hub release upload "${{ github.ref }}" \
              "spaceapi-dezentrale-client-${arch}.tar.xz" \
              "spaceapi-dezentrale-server-${arch}.tar.xz"
          done
