name: Standard tasks

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  test:
    runs-on: ubuntu-22.04
    container: rust:1.71
    steps:
      - uses: actions/checkout@v3
      - run: cargo test

  lint:
    runs-on: ubuntu-22.04
    container: rust:1.71
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy --all-targets --all-features -- -D warnings

  fmt:
    runs-on: ubuntu-22.04
    container: rust:1.71
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --all -- --check

  build:
    strategy:
      matrix:
        include:
          - arch: aarch64
            target: aarch64-unknown-linux-musl
            packages: "gcc-aarch64-linux-gnu musl-tools"
          - arch: armv6
            target: arm-unknown-linux-musleabihf
            packages: "gcc-arm-linux-gnueabihf musl-tools"
          - arch: armv7
            target: armv7-unknown-linux-musleabihf
            packages: "gcc-arm-linux-gnueabihf musl-tools"
          - arch: x86_64
            target: x86_64-unknown-linux-musl
            packages: "musl-tools"
    runs-on: ubuntu-22.04
    container: rust:latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          export DEBCONF_FRONTEND=noninteractive
          apt-get update
          apt-get upgrade --yes
          apt-get install --yes ${{ matrix.packages }}
          cargo build --target ${{ matrix.target }}

      - name: Archive server binaries
        uses: actions/upload-artifact@v3
        with:
          name: spaceapi-dezentrale-server-${{ matrix.arch }}
          path: |
            target/${{ matrix.target }}/*/spaceapi-dezentrale-server

      - name: Archive client binaries
        uses: actions/upload-artifact@v3
        with:
          name: spaceapi-dezentrale-client-${{ matrix.arch }}
          path: |
            target/${{ matrix.target }}/*/spaceapi-dezentrale-client
