name: Commit on non-main branch

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    container: rust:latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo test

  build:
    strategy:
      matrix:
        include:
          - arch: aarch64
            packages: "gcc-aarch64-linux-gnu musl-tools"
          - arch: x86_64
            packages: "musl-tools"
    runs-on: ubuntu-22.04
    container: rust:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          export DEBCONF_FRONTEND=noninteractive
          apt-get update
          apt-get upgrade --yes
          apt-get install --yes ${{ matrix.packages }}
          cargo build --target ${{ matrix.arch }}-unknown-linux-musl

      - name: Archive server binaries
        uses: actions/upload-artifact@v3
        with:
          name: spaceapi-dezentrale-server-${{ matrix.arch }}
          path: |
            target/${{ matrix.arch }}-unknown-linux-musl/*/spaceapi-dezentrale-server

      - name: Archive client binaries
        uses: actions/upload-artifact@v3
        with:
          name: spaceapi-dezentrale-client-${{ matrix.arch }}
          path: |
            target/${{ matrix.arch }}-unknown-linux-musl/*/spaceapi-dezentrale-client

  lint:
    runs-on: ubuntu-22.04
    container: rust:latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy --all-targets --all-features -- -D warnings
        continue-on-error: true

  fmt:
    runs-on: ubuntu-22.04
    container: rust:latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --all -- --check
        continue-on-error: true
